In [1]:
import pandas as pd
import numpy as np

In [2]:
!type examples/ex1.csv

命令语法不正确。

In [3]:
df = pd.read_csv("examples/ex1.csv")

In [4]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
!type examples/ex2.csv

命令语法不正确。

In [6]:
pd.read_csv("examples/ex2.csv", header = None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [7]:
pd.read_csv("examples/ex2.csv", names = ["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
names= ["a", "b", "c", "d", "message"]

In [9]:
pd.read_csv("examples/ex2.csv", names = names, index_col = "message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [10]:
!type examples/csv_mindex.csv

命令语法不正确。

In [11]:
parsed = pd.read_csv("examples/csv_mindex.csv",
                     index_col=["key1", "key2"])

In [12]:
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [14]:
!type examples/ex3.txt

命令语法不正确。

In [15]:
result = pd.read_csv("examples/ex3.txt", sep = "\s+")

In [16]:
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [17]:
!type examples/exa.csv

命令语法不正确。

In [18]:
pd.read_csv("examples/ex4.csv", skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [19]:
!type exmaples/ex5.csv

命令语法不正确。

In [20]:
result = pd.read_csv("examples/ex5.csv")

In [21]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [22]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [23]:
result = pd.read_csv("examples/ex5.csv", na_values = ["NULL"])

In [24]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [25]:
result2 = pd.read_csv("examples/ex5.csv", keep_default_na = False)

In [26]:
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [27]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [28]:
result3 = pd.read_csv("examples/ex5.csv", keep_default_na = False, na_values = ["NA"])

In [29]:
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [30]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [31]:
sentinels = {"message":["foo", "NA"], "something":["two"]}

In [32]:
pd.read_csv("examples/ex5.csv", na_values = sentinels, keep_default_na = False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN