# 10.1 How to Think About Group Operations

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.DataFrame({"key1" : ["a", "a", None, "b", "b", "a", None],
                   "key2" : pd.Series([1, 2, 1, 2, 1, None, 1], dtype="Int64"),
                   "data1" : np.random.standard_normal(7),
                   "data2" : np.random.standard_normal(7)})

In [4]:
df

   key1  key2     data1     data2
0     a     1  1.226724 -1.488056
1     a     2  0.212300  0.248324
2  None     1  2.050712 -0.235135
3     b     2  1.257127  1.644338
4     b     1 -0.325521 -0.458198
5     a  <NA> -1.189354  0.670638
6  None     1 -0.293124 -0.243083

In [5]:
grouped = df["data1"].groupby(df["key1"])

In [6]:
grouped

In [7]:
grouped.mean()

key1
a    0.083223
b    0.465803
Name: data1, dtype: float64

In [8]:
means = df["data1"].groupby([df["key1"], df["key2"]]).mean()

In [9]:
means

key1  key2
a     1       1.226724
      2       0.212300
b     1      -0.325521
      2       1.257127
Name: data1, dtype: float64

In [10]:
means.unstack()

key2         1         2
key1
a     1.226724  0.212300
b    -0.325521  1.257127

In [11]:
states = np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])

In [12]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [13]:
df["data1"].groupby([states, years]).mean()

CA  2005   -0.488527
    2006    2.050712
OH  2005    1.241926
    2006   -0.309323
Name: data1, dtype: float64

In [14]:
df.groupby("key1").mean()

      key2     data1     data2
key1
a      1.5  0.083223 -0.189698
b      1.5  0.465803  0.593070

In [16]:
df.groupby("key2")[["data1", "data2"]].mean()

         data1     data2
key2
1     0.664698 -0.606118
2     0.734713  0.946331

In [17]:
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    1     1.226724 -1.488056
     2     0.212300  0.248324
b    1    -0.325521 -0.458198
     2     1.257127  1.644338

In [18]:
df.groupby(["key1", "key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [19]:
df.groupby("key1", dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [20]:
df.groupby(["key1", "key2"], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [21]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

## 10.1.1 Iterating over Groups

In [22]:
for name, group in df.groupby("key1"):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1  1.226724 -1.488056
1    a     2  0.212300  0.248324
5    a  <NA> -1.189354  0.670638
b
  key1  key2     data1     data2
3    b     2  1.257127  1.644338
4    b     1 -0.325521 -0.458198

In [23]:
for (k1, k2), group in df.groupby(["key1", "key2"]):
    print((k1, k2))
    print(group)

('a', np.int64(1))
  key1  key2     data1     data2
0    a     1  1.226724 -1.488056
('a', np.int64(2))
  key1  key2   data1     data2
1    a     2  0.2123  0.248324
('b', np.int64(1))
  key1  key2     data1     data2
4    b     1 -0.325521 -0.458198
('b', np.int64(2))
  key1  key2     data1     data2
3    b     2  1.257127  1.644338

In [24]:
grouped = df.groupby({"key1":"key", "key2":"key",
                      "data1": "data", "data2": "data"}, axis = "columns")

C:\Users\34327\AppData\Local\Temp\ipykernel_15436\3867639031.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped = df.groupby({"key1":"key", "key2":"key",

In [25]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values)

data
      data1     data2
0  1.226724 -1.488056
1  0.212300  0.248324
2  2.050712 -0.235135
3  1.257127  1.644338
4 -0.325521 -0.458198
5 -1.189354  0.670638
6 -0.293124 -0.243083
key
   key1  key2
0     a     1
1     a     2
2  None     1
3     b     2
4     b     1
5     a  <NA>
6  None     1

## 10.1.2 Selecting a Column or Subset of Columns

In [26]:
df.groupby(["key1", "key2"])[["data2"]].mean()

              data2
key1 key2
a    1    -1.488056
     2     0.248324
b    1    -0.458198
     2     1.644338

In [27]:
s_grouped = df.groupby(["key1", "key2"])["data2"]

In [28]:
s_grouped

In [29]:
s_grouped.mean()

key1  key2
a     1      -1.488056
      2       0.248324
b     1      -0.458198
      2       1.644338
Name: data2, dtype: float64

In [30]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                      columns=["a", "b", "c", "d", "e"],
                      index=["Joe", "Steve", "Wanda", "Jill", "Trey"])

In [34]:
people.iloc[2:3, [1, 2]] = np.nan #加入一些空值

In [35]:
people

              a         b         c         d         e
Joe    1.995231 -0.635319 -0.228467  1.041847 -1.020590
Steve  0.355363  0.015577  1.421842  1.005324  0.553608
Wanda -0.149087       NaN       NaN -0.287192 -0.251624
Jill   0.090909  2.020829  0.669343 -1.641824 -0.662000
Trey   0.337368  0.287457 -0.214334  1.387035 -0.528021

In [36]:
mapping = {"a": "red", "b": "red", "c": "blue",
           "d": "blue", "e": "red", "f" : "orange"}

In [37]:
by_column = people.groupby(mapping, axis = "columns")

C:\Users\34327\AppData\Local\Temp\ipykernel_15436\4235764953.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column = people.groupby(mapping, axis = "columns")

In [39]:
by_column.sum()

           blue       red
Joe    0.813380  0.339321
Steve  2.427166  0.924549
Wanda -0.287192 -0.400712
Jill  -0.972481  1.449738
Trey   1.172700  0.096803

In [40]:
map_series = pd.Series(mapping)

In [41]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [42]:
people.groupby(map_series, axis = "columns").count()

C:\Users\34327\AppData\Local\Temp\ipykernel_15436\1498336565.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  people.groupby(map_series, axis = "columns").count()

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [43]:
people.groupby(len).sum()

          a         b         c         d         e
3  1.995231 -0.635319 -0.228467  1.041847 -1.020590
4  0.428277  2.308286  0.455009 -0.254790 -1.190021
5  0.206276  0.015577  1.421842  0.718132  0.301984

In [44]:
key_list = ["one", "one", "one", "two", "two"]

In [45]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one  1.995231 -0.635319 -0.228467  1.041847 -1.020590
4 two  0.090909  0.287457 -0.214334 -1.641824 -0.662000
5 one -0.149087  0.015577  1.421842 -0.287192 -0.251624

In [48]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"], #第一层
                                     [1, 3, 5, 1, 3]], #第二层
                                    names=["cty", "tenor"]) #两层分别叫city和tenor

In [47]:
columns

MultiIndex([('US', 1),
            ('US', 3),
            ('US', 5),
            ('JP', 1),
            ('JP', 3)],
           names=['cty', 'tenor'])

In [49]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns = columns)

In [50]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0     -0.132562  0.602773 -0.415198 -0.455462  1.507045
1     -0.106508 -2.088608 -0.486630  2.382114  0.750735
2     -0.392547  0.321144 -0.266210  1.043774  0.009108
3      0.823046 -1.540992  0.177090  1.540871  1.461196

In [51]:
hier_df.groupby(level = "cty", axis = "columns").count()

C:\Users\34327\AppData\Local\Temp\ipykernel_15436\1479305392.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level = "cty", axis = "columns").count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

## 10.2 Data Aggregation

In [52]:
df

   key1  key2     data1     data2
0     a     1  1.226724 -1.488056
1     a     2  0.212300  0.248324
2  None     1  2.050712 -0.235135
3     b     2  1.257127  1.644338
4     b     1 -0.325521 -0.458198
5     a  <NA> -1.189354  0.670638
6  None     1 -0.293124 -0.243083

In [53]:
grouped = df.groupby("key1")

In [54]:
grouped["data1"].nsmallest(2)

key1
a     5   -1.189354
      1    0.212300
b     4   -0.325521
      3    1.257127
Name: data1, dtype: float64

In [55]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [56]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  2.416078  2.158694
b        1  1.582648  2.102536

In [57]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0  0.083223  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0  0.465803  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     0.719512  1.226724   3.0 -0.189698  1.144066 -1.488056 -0.619866
b     0.861465  1.257127   2.0  0.593070  1.486718 -0.458198  0.067436


           50%       75%       max
key1
a     0.248324  0.459481  0.670638
b     0.593070  1.118704  1.644338

[2 rows x 24 columns]

In [58]:
tips = pd.read_csv("examples/tips.csv")

In [59]:
tips.head(10)

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4
5       25.29  4.71     No  Sun  Dinner     4
6        8.77  2.00     No  Sun  Dinner     2
7       26.88  3.12     No  Sun  Dinner     4
8       15.04  1.96     No  Sun  Dinner     2
9       14.78  3.23     No  Sun  Dinner     2

In [60]:
tips["tip_pct"] = tips["tip"]/tips["total_bill"]

In [61]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [62]:
grouped = tips.groupby(["day", "smoker"])

In [63]:
grouped_pct = grouped["tip_pct"]

In [64]:
grouped_pct.agg("mean")

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [65]:
grouped_pct.agg(["mean", "std", peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240