# 10.1 How to Think About Group Operations

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.DataFrame({"key1" : ["a", "a", None, "b", "b", "a", None],
                   "key2" : pd.Series([1, 2, 1, 2, 1, None, 1], dtype="Int64"),
                   "data1" : np.random.standard_normal(7),
                   "data2" : np.random.standard_normal(7)})

In [4]:
df

   key1  key2     data1     data2
0     a     1  0.688341  1.938082
1     a     2  0.540926 -0.033687
2  None     1  0.918132  0.093144
3     b     2 -1.212064  0.414445
4     b     1  0.842958 -0.542426
5     a  <NA>  1.489329 -1.234917
6  None     1 -0.509834 -0.411601

In [5]:
grouped = df["data1"].groupby(df["key1"])

In [6]:
grouped

In [7]:
grouped.mean()

key1
a    0.906199
b   -0.184553
Name: data1, dtype: float64

In [8]:
means = df["data1"].groupby([df["key1"], df["key2"]]).mean()

In [9]:
means

key1  key2
a     1       0.688341
      2       0.540926
b     1       0.842958
      2      -1.212064
Name: data1, dtype: float64

In [10]:
means.unstack()

key2         1         2
key1
a     0.688341  0.540926
b     0.842958 -1.212064

In [11]:
states = np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])

In [12]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [13]:
df["data1"].groupby([states, years]).mean()

CA  2005    1.015128
    2006    0.918132
OH  2005   -0.261862
    2006    0.166562
Name: data1, dtype: float64

In [14]:
df.groupby("key1").mean()

      key2     data1    data2
key1
a      1.5  0.906199  0.22316
b      1.5 -0.184553 -0.06399

In [15]:
df.groupby("key2")[["data1", "data2"]].mean()

         data1     data2
key2
1     0.484899  0.269300
2    -0.335569  0.190379

In [16]:
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    1     0.688341  1.938082
     2     0.540926 -0.033687
b    1     0.842958 -0.542426
     2    -1.212064  0.414445

In [17]:
df.groupby(["key1", "key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [18]:
df.groupby("key1", dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [19]:
df.groupby(["key1", "key2"], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [20]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

## 10.1.1 Iterating over Groups

In [21]:
for name, group in df.groupby("key1"):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1  0.688341  1.938082
1    a     2  0.540926 -0.033687
5    a  <NA>  1.489329 -1.234917
b
  key1  key2     data1     data2
3    b     2 -1.212064  0.414445
4    b     1  0.842958 -0.542426

In [22]:
for (k1, k2), group in df.groupby(["key1", "key2"]):
    print((k1, k2))
    print(group)

('a', np.int64(1))
  key1  key2     data1     data2
0    a     1  0.688341  1.938082
('a', np.int64(2))
  key1  key2     data1     data2
1    a     2  0.540926 -0.033687
('b', np.int64(1))
  key1  key2     data1     data2
4    b     1  0.842958 -0.542426
('b', np.int64(2))
  key1  key2     data1     data2
3    b     2 -1.212064  0.414445

In [23]:
grouped = df.groupby({"key1":"key", "key2":"key",
                      "data1": "data", "data2": "data"}, axis = "columns")

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\3867639031.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped = df.groupby({"key1":"key", "key2":"key",

In [24]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values)

data
      data1     data2
0  0.688341  1.938082
1  0.540926 -0.033687
2  0.918132  0.093144
3 -1.212064  0.414445
4  0.842958 -0.542426
5  1.489329 -1.234917
6 -0.509834 -0.411601
key
   key1  key2
0     a     1
1     a     2
2  None     1
3     b     2
4     b     1
5     a  <NA>
6  None     1

## 10.1.2 Selecting a Column or Subset of Columns

In [25]:
df.groupby(["key1", "key2"])[["data2"]].mean()

              data2
key1 key2
a    1     1.938082
     2    -0.033687
b    1    -0.542426
     2     0.414445

In [26]:
s_grouped = df.groupby(["key1", "key2"])["data2"]

In [27]:
s_grouped

In [28]:
s_grouped.mean()

key1  key2
a     1       1.938082
      2      -0.033687
b     1      -0.542426
      2       0.414445
Name: data2, dtype: float64

In [29]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                      columns=["a", "b", "c", "d", "e"],
                      index=["Joe", "Steve", "Wanda", "Jill", "Trey"])

In [30]:
people.iloc[2:3, [1, 2]] = np.nan #加入一些空值

In [31]:
people

              a         b         c         d         e
Joe    0.200144  0.729192 -0.545598 -1.548382  0.030217
Steve  2.752830  0.187243  1.049143 -0.746422 -0.966103
Wanda -2.844267       NaN       NaN -0.869947 -0.909333
Jill  -0.530281  0.613521 -0.431198  0.091901 -0.171132
Trey  -0.822945 -0.061417 -0.876639 -1.567956  0.346996

In [32]:
mapping = {"a": "red", "b": "red", "c": "blue",
           "d": "blue", "e": "red", "f" : "orange"}

In [33]:
by_column = people.groupby(mapping, axis = "columns")

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\4235764953.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column = people.groupby(mapping, axis = "columns")

In [34]:
by_column.sum()

           blue       red
Joe   -2.093980  0.959552
Steve  0.302721  1.973970
Wanda -0.869947 -3.753600
Jill  -0.339297 -0.087892
Trey  -2.444595 -0.537366

In [35]:
map_series = pd.Series(mapping)

In [36]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [37]:
people.groupby(map_series, axis = "columns").count()

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\1498336565.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  people.groupby(map_series, axis = "columns").count()

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [38]:
people.groupby(len).sum()

          a         b         c         d         e
3  0.200144  0.729192 -0.545598 -1.548382  0.030217
4 -1.353226  0.552104 -1.307837 -1.476055  0.175864
5 -0.091437  0.187243  1.049143 -1.616370 -1.875436

In [39]:
key_list = ["one", "one", "one", "two", "two"]

In [40]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one  0.200144  0.729192 -0.545598 -1.548382  0.030217
4 two -0.822945 -0.061417 -0.876639 -1.567956 -0.171132
5 one -2.844267  0.187243  1.049143 -0.869947 -0.966103

In [41]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"], #第一层
                                     [1, 3, 5, 1, 3]], #第二层
                                    names=["cty", "tenor"]) #两层分别叫city和tenor

In [42]:
columns

MultiIndex([('US', 1),
            ('US', 3),
            ('US', 5),
            ('JP', 1),
            ('JP', 3)],
           names=['cty', 'tenor'])

In [43]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns = columns)

In [44]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0      0.079651  0.191787 -0.013252 -0.859836  0.164914
1     -0.249048  0.848490  2.169393  2.643195  0.824850
2     -0.843892  0.660737  1.581872  0.992953  0.103557
3      0.191326 -0.616469 -0.138879 -0.351693  0.480696

In [45]:
hier_df.groupby(level = "cty", axis = "columns").count()

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\1479305392.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level = "cty", axis = "columns").count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

## 10.2 Data Aggregation

In [46]:
df

   key1  key2     data1     data2
0     a     1  0.688341  1.938082
1     a     2  0.540926 -0.033687
2  None     1  0.918132  0.093144
3     b     2 -1.212064  0.414445
4     b     1  0.842958 -0.542426
5     a  <NA>  1.489329 -1.234917
6  None     1 -0.509834 -0.411601

In [47]:
grouped = df.groupby("key1")

In [48]:
grouped["data1"].nsmallest(2)

key1
a     1    0.540926
      0    0.688341
b     3   -1.212064
      4    0.842958
Name: data1, dtype: float64

In [49]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [50]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  0.948403  3.172999
b        1  2.055023  0.956871

In [51]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0  0.906199  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0 -0.184553  ...

                         data2                                         \
           75%       max count     mean       std       min       25%
key1
a     1.088835  1.489329   3.0  0.22316  1.602017 -1.234917 -0.634302
b     0.329203  0.842958   2.0 -0.06399  0.676610 -0.542426 -0.303208


           50%       75%       max
key1
a    -0.033687  0.952198  1.938082
b    -0.063990  0.175227  0.414445

[2 rows x 24 columns]

### 10.2.1 Column-Wise and Multiple Function Application

In [52]:
tips = pd.read_csv("examples/tips.csv")

In [53]:
tips.head(10)

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4
5       25.29  4.71     No  Sun  Dinner     4
6        8.77  2.00     No  Sun  Dinner     2
7       26.88  3.12     No  Sun  Dinner     4
8       15.04  1.96     No  Sun  Dinner     2
9       14.78  3.23     No  Sun  Dinner     2

In [54]:
tips["tip_pct"] = tips["tip"] / tips["total_bill"]

In [55]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [56]:
grouped = tips.groupby(["day", "smoker"])

In [57]:
grouped_pct = grouped["tip_pct"]

In [58]:
grouped_pct.agg("mean")

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [59]:
grouped_pct.agg(["mean", "std", peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [60]:
grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\1734782830.py:1: FutureWarning: The provided callable <function std at 0x000001C97501BE20> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.028123
     Yes     0.174783  0.051293
Sat  No      0.158048  0.039767
     Yes     0.147906  0.061375
Sun  No      0.160113  0.042347
     Yes     0.187250  0.154134
Thur No      0.160298  0.038774
     Yes     0.163863  0.039389

In [61]:
functions = ["count", "mean", "max"]

In [62]:
result = grouped[["tip_pct", "total_bill"]].agg(functions)

In [63]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [64]:
result["tip_pct"]

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [65]:
ftuples = [("Average", "mean"), ("Variables", np.var)]

In [66]:
grouped[["tip_pct", "total_bill"]].agg(ftuples)

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\365474927.py:1: FutureWarning: The provided callable <function var at 0x000001C97501BF60> is currently using SeriesGroupBy.var. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "var" instead.
  grouped[["tip_pct", "total_bill"]].agg(ftuples)

              tip_pct           total_bill
              Average Variables    Average   Variables
day  smoker
Fri  No      0.151650  0.000791  18.420000   25.596333
     Yes     0.174783  0.002631  16.813333   82.562438
Sat  No      0.158048  0.001581  19.661778   79.908965
     Yes     0.147906  0.003767  21.276667  101.387535
Sun  No      0.160113  0.001793  20.506667   66.099980
     Yes     0.187250  0.023757  24.120000  109.046044
Thur No      0.160298  0.001503  17.113111   59.625081
     Yes     0.163863  0.001551  19.190588   69.808518

In [67]:
grouped.agg({"tip": np.max, "size": "sum"})

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\3453032214.py:1: FutureWarning: The provided callable <function max at 0x000001C97501B2E0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grouped.agg({"tip": np.max, "size": "sum"})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [68]:
grouped.agg({"tip_pct": ["min", "max", "mean", "std"], 
             "size": "sum"})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [69]:
tips.groupby(["day", "smoker"], as_index=False).mean(numeric_only = True)

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863

In [70]:
def top(df, n=5, column="tip_pct"):
    return df.sort_values(column, ascending = False)[:n]

In [71]:
top(tips, n=6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [72]:
tips.groupby("smoker").apply(top)

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\2530541573.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker").apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     232       11.61  3.39     No   Sat  Dinner     2  0.291990
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       88        24.71  5.85     No  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [73]:
tips.groupby(["smoker", "day"]).apply(top, n=1, column = "total_bill")

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\3038737715.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby(["smoker", "day"]).apply(top, n=1, column = "total_bill")

                 total_bill    tip smoker   day    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25     No   Fri  Dinner     2  0.142857
       Sat  212       48.33   9.00     No   Sat  Dinner     4  0.186220
       Sun  156       48.17   5.00     No   Sun  Dinner     6  0.103799
       Thur 142       41.19   5.00     No  Thur   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73    Yes   Fri  Dinner     4  0.117750
       Sat  170       50.81  10.00    Yes   Sat  Dinner     3  0.196812
       Sun  182       45.35   3.50    Yes   Sun  Dinner     3  0.077178
       Thur 197       43.11   5.00    Yes  Thur   Lunch     4  0.115982

In [74]:
result = tips.groupby("smoker")["tip_pct"].describe()

In [75]:
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [76]:
result.unstack("smoker")

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [77]:
tips.groupby("smoker", group_keys =False).apply(top)

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\2845968930.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker", group_keys =False).apply(top)

     total_bill   tip smoker   day    time  size   tip_pct
232       11.61  3.39     No   Sat  Dinner     2  0.291990
149        7.51  2.00     No  Thur   Lunch     2  0.266312
51        10.29  2.60     No   Sun  Dinner     2  0.252672
185       20.69  5.00     No   Sun  Dinner     5  0.241663
88        24.71  5.85     No  Thur   Lunch     2  0.236746
172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [78]:
frame = pd.DataFrame({"data1": np.random.standard_normal(1000), 
                      "data2": np.random.standard_normal(1000)})

In [79]:
frame.head()

      data1     data2
0  1.206273 -1.308296
1 -0.289568  1.750106
2  0.801479 -1.000608
3 -0.969419 -0.346346
4  0.415111 -1.532561

In [80]:
quartiles = pd.cut(frame["data1"], 4)

In [81]:
quartiles.head(10)

0     (-0.147, 1.608]
1    (-1.901, -0.147]
2     (-0.147, 1.608]
3    (-1.901, -0.147]
4     (-0.147, 1.608]
5     (-0.147, 1.608]
6     (-0.147, 1.608]
7    (-1.901, -0.147]
8     (-0.147, 1.608]
9     (-0.147, 1.608]
Name: data1, dtype: category
Categories (4, interval[float64, right]): [(-3.662, -1.901] < (-1.901, -0.147] < (-0.147, 1.608] < (1.608, 3.362]]

In [82]:
def get_stats(group):
    return pd.DataFrame(
        {
            "min": group.min(), 
            "max": group.max(), 
            "count": group.count(), 
            "mean": group.mean()
        }
    )

In [83]:
grouped = frame.groupby(quartiles)

C:\Users\34327\AppData\Local\Temp\ipykernel_9856\4041437760.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = frame.groupby(quartiles)

In [84]:
grouped.apply(get_stats)

                             min       max  count      mean
data1
(-3.662, -1.901] data1 -3.655413 -1.901273     31 -2.334283
                 data2 -3.324625  2.126279     31 -0.354110
(-1.901, -0.147] data1 -1.900319 -0.148196    385 -0.807356
                 data2 -3.149889  2.553213    385  0.016046
(-0.147, 1.608]  data1 -0.142914  1.601774    512  0.574874
                 data2 -2.678294  3.139389    512 -0.000976
(1.608, 3.362]   data1  1.612682  3.362086     72  2.006294
                 data2 -2.480304  2.531432     72 -0.057428

In [85]:
grouped.agg(["min", "max", "count", "mean"])

                     data1                               data2            \
                       min       max count      mean       min       max
data1
(-3.662, -1.901] -3.655413 -1.901273    31 -2.334283 -3.324625  2.126279
(-1.901, -0.147] -1.900319 -0.148196   385 -0.807356 -3.149889  2.553213
(-0.147, 1.608]  -0.142914  1.601774   512  0.574874 -2.678294  3.139389
(1.608, 3.362]    1.612682  3.362086    72  2.006294 -2.480304  2.531432


                 count      mean
data1
(-3.662, -1.901]    31 -0.354110
(-1.901, -0.147]   385  0.016046
(-0.147, 1.608]    512 -0.000976
(1.608, 3.362]      72 -0.057428

In [86]:
quartiles_samp = pd.qcut(frame["data1"], 4, labels = False)

In [87]:
quartiles_samp.head(10)

0    3
1    1
2    3
3    0
4    2
5    2
6    2
7    1
8    1
9    2
Name: data1, dtype: int64

In [88]:
grouped.apply(get_stats)

                             min       max  count      mean
data1
(-3.662, -1.901] data1 -3.655413 -1.901273     31 -2.334283
                 data2 -3.324625  2.126279     31 -0.354110
(-1.901, -0.147] data1 -1.900319 -0.148196    385 -0.807356
                 data2 -3.149889  2.553213    385  0.016046
(-0.147, 1.608]  data1 -0.142914  1.601774    512  0.574874
                 data2 -2.678294  3.139389    512 -0.000976
(1.608, 3.362]   data1  1.612682  3.362086     72  2.006294
                 data2 -2.480304  2.531432     72 -0.057428

In [89]:
s = pd.Series(np.random.standard_normal(6))

In [90]:
s[::2] = np.nan

In [91]:
s

0         NaN
1    0.055126
2         NaN
3    0.378181
4         NaN
5    0.778686
dtype: float64

In [92]:
s.fillna(s.mean())

0    0.403998
1    0.055126
2    0.403998
3    0.378181
4    0.403998
5    0.778686
dtype: float64

In [93]:
states = ["Ohio", "New York", "Vermont", "Florida",
          "Oregon", "Nevada", "California", "Idaho"]

In [94]:
group_key = ["East", "East", "East", "East",
             "West", "West", "West", "West"]

In [95]:
data = pd.Series(np.random.standard_normal(8), index = states)

In [96]:
data

Ohio         -0.594247
New York      0.272826
Vermont      -1.142897
Florida      -2.053783
Oregon        1.135112
Nevada        1.158509
California    2.109875
Idaho         1.152522
dtype: float64

In [97]:
data[["Vermont", "Nevada", "Idaho"]] = np.nan

In [98]:
data

Ohio         -0.594247
New York      0.272826
Vermont            NaN
Florida      -2.053783
Oregon        1.135112
Nevada             NaN
California    2.109875
Idaho              NaN
dtype: float64

In [99]:
data.groupby(group_key).size()

East    4
West    4
dtype: int64

In [100]:
data.groupby(group_key).count()

East    3
West    2
dtype: int64

In [101]:
data.groupby(group_key).mean()

East   -0.791735
West    1.622494
dtype: float64

In [102]:
def fill_mean(group):
    return group.fillna(group.mean())

In [103]:
data.groupby(group_key).apply(fill_mean)

East  Ohio         -0.594247
      New York      0.272826
      Vermont      -0.791735
      Florida      -2.053783
West  Oregon        1.135112
      Nevada        1.622494
      California    2.109875
      Idaho         1.622494
dtype: float64

In [104]:
fill_values = {"East": 0.5, "West": -1}

In [105]:
def fill_func(group):
    return group.fillna(fill_values[group.name])

In [106]:
data.groupby(group_key).apply(fill_func)

East  Ohio         -0.594247
      New York      0.272826
      Vermont       0.500000
      Florida      -2.053783
West  Oregon        1.135112
      Nevada       -1.000000
      California    2.109875
      Idaho        -1.000000
dtype: float64

In [107]:
suits = ["H", "S", "C", "D"]  # Hearts, Spades, Clubs, Diamonds（红桃，黑桃，梅花，方块）
card_val = (list(range(1, 11)) + [10] * 3) * 4
base_names = ["A"] + list(range(2, 11)) + ["J", "K", "Q"]
cards = []
for suit in suits:
    cards.extend(str(num) + suit for num in base_names)

deck = pd.Series(card_val, index=cards)

In [108]:
deck.head(13)

AH      1
2H      2
3H      3
4H      4
5H      5
6H      6
7H      7
8H      8
9H      9
10H    10
JH     10
KH     10
QH     10
dtype: int64

In [109]:
def draw(deck, n=5):
    return deck.sample(n)

In [110]:
draw(deck)

2S     2
KH    10
2D     2
2C     2
6H     6
dtype: int64

In [111]:
def get_suit(card):
    #最后一个字母是花色
    return card[-1]

In [112]:
deck.groupby(get_suit).apply(draw, n=2)

C  9C     9
   5C     5
D  5D     5
   KD    10
H  JH    10
   9H     9
S  7S     7
   2S     2
dtype: int64

In [113]:
deck.groupby(get_suit, group_keys = False).apply(draw, n=2)

QC     10
10C    10
3D      3
KD     10
8H      8
KH     10
5S      5
KS     10
dtype: int64

finishing 10.3.4 example

## 10.4 Group Transforms and “Unwrapped” GroupBys

In [114]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
                   'value': np.arange(12.)})

In [115]:
df

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [116]:
g = df.groupby("key")["value"]

In [117]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [118]:
def get_mean(group):
    return group.mean()

In [119]:
g.transform(get_mean)

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [120]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [121]:
def times_two(group):
    return group * 2

In [122]:
g.transform(times_two)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [123]:
def get_ranks(group):
    return group.rank(ascending = False)

In [124]:
g.transform(get_ranks)

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [125]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [126]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [127]:
g.apply(normalize)

key
a    0    -1.161895
     3    -0.387298
     6     0.387298
     9     1.161895
b    1    -1.161895
     4    -0.387298
     7     0.387298
     10    1.161895
c    2    -1.161895
     5    -0.387298
     8     0.387298
     11    1.161895
Name: value, dtype: float64

In [128]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [129]:
g.transform('sum')

0     18.0
1     22.0
2     26.0
3     18.0
4     22.0
5     26.0
6     18.0
7     22.0
8     26.0
9     18.0
10    22.0
11    26.0
Name: value, dtype: float64

In [130]:
normalized = (df['value'] - g.transform('mean')) / g.transform('std')

In [131]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

# 10.5 Pivot Tables and Cross-Tabulation

## pivot_table

In [132]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [133]:
tips.pivot_table(index=["day", "smoker"],
                 values=["total_bill", "tip", "size", "tip_pct"])

                 size       tip   tip_pct  total_bill
day  smoker
Fri  No      2.250000  2.812500  0.151650   18.420000
     Yes     2.066667  2.714000  0.174783   16.813333
Sat  No      2.555556  3.102889  0.158048   19.661778
     Yes     2.476190  2.875476  0.147906   21.276667
Sun  No      2.929825  3.167895  0.160113   20.506667
     Yes     2.578947  3.516842  0.187250   24.120000
Thur No      2.488889  2.673778  0.160298   17.113111
     Yes     2.352941  3.030000  0.163863   19.190588

In [134]:
tips.pivot_table(index = ["time", "day"], 
                 columns = "smoker", 
                 values = ["tip_pct", "size"])

                 size             tip_pct
smoker             No       Yes        No       Yes
time   day
Dinner Fri   2.000000  2.222222  0.139622  0.165347
       Sat   2.555556  2.476190  0.158048  0.147906
       Sun   2.929825  2.578947  0.160113  0.187250
       Thur  2.000000       NaN  0.159744       NaN
Lunch  Fri   3.000000  1.833333  0.187735  0.188937
       Thur  2.500000  2.352941  0.160311  0.163863

In [135]:
tips.pivot_table(index = ["time", "day"], columns = "smoker", 
                 values = ["tip_pct", "size"], margins = True)

                 size                       tip_pct
smoker             No       Yes       All        No       Yes       All
time   day
Dinner Fri   2.000000  2.222222  2.166667  0.139622  0.165347  0.158916
       Sat   2.555556  2.476190  2.517241  0.158048  0.147906  0.153152
       Sun   2.929825  2.578947  2.842105  0.160113  0.187250  0.166897
       Thur  2.000000       NaN  2.000000  0.159744       NaN  0.159744
Lunch  Fri   3.000000  1.833333  2.000000  0.187735  0.188937  0.188765
       Thur  2.500000  2.352941  2.459016  0.160311  0.163863  0.161301
All          2.668874  2.408602  2.569672  0.159328  0.163196  0.160803

In [136]:
tips.pivot_table(index = ["time", "smoker"], columns = "day", 
                 values = "tip_pct", aggfunc = len, margins = True)

day             Fri   Sat   Sun  Thur  All
time   smoker
Dinner No       3.0  45.0  57.0   1.0  106
       Yes      9.0  42.0  19.0   NaN   70
Lunch  No       1.0   NaN   NaN  44.0   45
       Yes      6.0   NaN   NaN  17.0   23
All            19.0  87.0  76.0  62.0  244

In [137]:
tips.pivot_table(index = ["time", "size", "smoker"], 
                 columns = "day", 
                 values = "tip_pct", 
                 fill_value = 0)

day                      Fri       Sat       Sun      Thur
time   size smoker
Dinner 1    No      0.000000  0.137931  0.000000  0.000000
            Yes     0.000000  0.325733  0.000000  0.000000
       2    No      0.139622  0.162705  0.168859  0.159744
            Yes     0.171297  0.148668  0.207893  0.000000
       3    No      0.000000  0.154661  0.152663  0.000000
            Yes     0.000000  0.144995  0.152660  0.000000
       4    No      0.000000  0.150096  0.148143  0.000000
            Yes     0.117750  0.124515  0.193370  0.000000
       5    No      0.000000  0.000000  0.206928  0.000000
            Yes     0.000000  0.106572  0.065660  0.000000
       6    No      0.000000  0.000000  0.103799  0.000000
Lunch  1    No      0.000000  0.000000  0.000000  0.181728
            Yes     0.223776  0.000000  0.000000  0.000000
       2    No      0.000000  0.000000  0.000000  0.166005
            Yes     0.181969  0.000000  0.000000  0.158843
       3    No      0.187735  0.000000  0.000000  0.084246
            Yes     0.000000  0.000000  0.000000  0.204952
       4    No      0.000000  0.000000  0.000000  0.138919
            Yes     0.000000  0.000000  0.000000  0.155410
       5    No      0.000000  0.000000  0.000000  0.121389
       6    No      0.000000  0.000000  0.000000  0.173706

## cross_tabulation

In [140]:
from io import StringIO

In [141]:
data = """Sample  Nationality  Handedness
1   USA  Right-handed
2   Japan    Left-handed
3   USA  Right-handed
4   Japan    Right-handed
5   Japan    Left-handed
6   Japan    Right-handed
7   USA  Right-handed
8   USA  Left-handed
9   Japan    Right-handed
10  USA  Right-handed"""

In [142]:
data = pd.read_table(StringIO(data), sep="\s+")

In [143]:
data

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

In [146]:
pd.crosstab(data["Nationality"], data["Handedness"], margins = True)

Handedness   Left-handed  Right-handed  All
Nationality
Japan                  2             3    5
USA                    1             4    5
All                    3             7   10

In [148]:
pd.crosstab([tips["time"], tips["day"]], tips["smoker"], margins = True)

smoker        No  Yes  All
time   day
Dinner Fri     3    9   12
       Sat    45   42   87
       Sun    57   19   76
       Thur    1    0    1
Lunch  Fri     1    6    7
       Thur   44   17   61
All          151   93  244