# 10.1 How to Think About Group Operations

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.DataFrame({"key1" : ["a", "a", None, "b", "b", "a", None],
                   "key2" : pd.Series([1, 2, 1, 2, 1, None, 1], dtype="Int64"),
                   "data1" : np.random.standard_normal(7),
                   "data2" : np.random.standard_normal(7)})

In [4]:
df

   key1  key2     data1     data2
0     a     1  0.596134 -0.510661
1     a     2 -0.769028  0.508013
2  None     1  1.102403 -0.562956
3     b     2 -0.664217  0.609987
4     b     1  1.666605 -0.935791
5     a  <NA> -0.963726 -1.251459
6  None     1  0.327655  1.263406

In [5]:
grouped = df["data1"].groupby(df["key1"])

In [6]:
grouped

In [7]:
grouped.mean()

key1
a   -0.378873
b    0.501194
Name: data1, dtype: float64

In [8]:
means = df["data1"].groupby([df["key1"], df["key2"]]).mean()

In [9]:
means

key1  key2
a     1       0.596134
      2      -0.769028
b     1       1.666605
      2      -0.664217
Name: data1, dtype: float64

In [10]:
means.unstack()

key2         1         2
key1
a     0.596134 -0.769028
b     1.666605 -0.664217

In [11]:
states = np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])

In [12]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [13]:
df["data1"].groupby([states, years]).mean()

CA  2005   -0.866377
    2006    1.102403
OH  2005   -0.034042
    2006    0.997130
Name: data1, dtype: float64

In [14]:
df.groupby("key1").mean()

      key2     data1     data2
key1
a      1.5 -0.378873 -0.418035
b      1.5  0.501194 -0.162902

In [15]:
df.groupby("key2")[["data1", "data2"]].mean()

         data1   data2
key2
1     0.923199 -0.1865
2    -0.716623  0.5590

In [16]:
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    1     0.596134 -0.510661
     2    -0.769028  0.508013
b    1     1.666605 -0.935791
     2    -0.664217  0.609987

In [17]:
df.groupby(["key1", "key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [18]:
df.groupby("key1", dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [19]:
df.groupby(["key1", "key2"], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [20]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

## 10.1.1 Iterating over Groups

In [21]:
for name, group in df.groupby("key1"):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1  0.596134 -0.510661
1    a     2 -0.769028  0.508013
5    a  <NA> -0.963726 -1.251459
b
  key1  key2     data1     data2
3    b     2 -0.664217  0.609987
4    b     1  1.666605 -0.935791

In [22]:
for (k1, k2), group in df.groupby(["key1", "key2"]):
    print((k1, k2))
    print(group)

('a', np.int64(1))
  key1  key2     data1     data2
0    a     1  0.596134 -0.510661
('a', np.int64(2))
  key1  key2     data1     data2
1    a     2 -0.769028  0.508013
('b', np.int64(1))
  key1  key2     data1     data2
4    b     1  1.666605 -0.935791
('b', np.int64(2))
  key1  key2     data1     data2
3    b     2 -0.664217  0.609987

In [23]:
grouped = df.groupby({"key1":"key", "key2":"key",
                      "data1": "data", "data2": "data"}, axis = "columns")

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\3867639031.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped = df.groupby({"key1":"key", "key2":"key",

In [24]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values)

data
      data1     data2
0  0.596134 -0.510661
1 -0.769028  0.508013
2  1.102403 -0.562956
3 -0.664217  0.609987
4  1.666605 -0.935791
5 -0.963726 -1.251459
6  0.327655  1.263406
key
   key1  key2
0     a     1
1     a     2
2  None     1
3     b     2
4     b     1
5     a  <NA>
6  None     1

## 10.1.2 Selecting a Column or Subset of Columns

In [25]:
df.groupby(["key1", "key2"])[["data2"]].mean()

              data2
key1 key2
a    1    -0.510661
     2     0.508013
b    1    -0.935791
     2     0.609987

In [26]:
s_grouped = df.groupby(["key1", "key2"])["data2"]

In [27]:
s_grouped

In [28]:
s_grouped.mean()

key1  key2
a     1      -0.510661
      2       0.508013
b     1      -0.935791
      2       0.609987
Name: data2, dtype: float64

In [29]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                      columns=["a", "b", "c", "d", "e"],
                      index=["Joe", "Steve", "Wanda", "Jill", "Trey"])

In [30]:
people.iloc[2:3, [1, 2]] = np.nan #加入一些空值

In [31]:
people

              a         b         c         d         e
Joe    0.900268  1.600011 -0.164375  1.059125 -0.226657
Steve  0.171379  0.735861 -0.818010 -0.671770  1.705010
Wanda -0.149006       NaN       NaN  0.541819  0.326787
Jill   0.044123  0.876285  0.406505  0.894474 -1.163800
Trey  -0.919873 -0.514243  0.938987  0.848753  0.955944

In [32]:
mapping = {"a": "red", "b": "red", "c": "blue",
           "d": "blue", "e": "red", "f" : "orange"}

In [33]:
by_column = people.groupby(mapping, axis = "columns")

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\4235764953.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column = people.groupby(mapping, axis = "columns")

In [34]:
by_column.sum()

           blue       red
Joe    0.894750  2.273622
Steve -1.489780  2.612250
Wanda  0.541819  0.177780
Jill   1.300979 -0.243392
Trey   1.787740 -0.478172

In [35]:
map_series = pd.Series(mapping)

In [36]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [37]:
people.groupby(map_series, axis = "columns").count()

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\1498336565.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  people.groupby(map_series, axis = "columns").count()

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [38]:
people.groupby(len).sum()

          a         b         c         d         e
3  0.900268  1.600011 -0.164375  1.059125 -0.226657
4 -0.875750  0.362042  1.345492  1.743227 -0.207855
5  0.022373  0.735861 -0.818010 -0.129951  2.031796

In [39]:
key_list = ["one", "one", "one", "two", "two"]

In [40]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one  0.900268  1.600011 -0.164375  1.059125 -0.226657
4 two -0.919873 -0.514243  0.406505  0.848753 -1.163800
5 one -0.149006  0.735861 -0.818010 -0.671770  0.326787

In [41]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"], #第一层
                                     [1, 3, 5, 1, 3]], #第二层
                                    names=["cty", "tenor"]) #两层分别叫city和tenor

In [42]:
columns

MultiIndex([('US', 1),
            ('US', 3),
            ('US', 5),
            ('JP', 1),
            ('JP', 3)],
           names=['cty', 'tenor'])

In [43]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns = columns)

In [44]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0     -0.148702  0.766719  0.913740  0.658924 -0.419074
1     -0.282886 -1.155287  1.566398  0.214652  0.786895
2      1.199961  1.118215  2.726527 -0.185533 -0.752535
3      1.214645 -0.460274 -0.551488  0.466375  0.862789

In [45]:
hier_df.groupby(level = "cty", axis = "columns").count()

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\1479305392.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level = "cty", axis = "columns").count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

## 10.2 Data Aggregation

In [46]:
df

   key1  key2     data1     data2
0     a     1  0.596134 -0.510661
1     a     2 -0.769028  0.508013
2  None     1  1.102403 -0.562956
3     b     2 -0.664217  0.609987
4     b     1  1.666605 -0.935791
5     a  <NA> -0.963726 -1.251459
6  None     1  0.327655  1.263406

In [47]:
grouped = df.groupby("key1")

In [48]:
grouped["data1"].nsmallest(2)

key1
a     5   -0.963726
      1   -0.769028
b     3   -0.664217
      4    1.666605
Name: data1, dtype: float64

In [49]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [50]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  1.559860  1.759472
b        1  2.330822  1.545778

In [51]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0 -0.378873  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0  0.501194  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a    -0.086447  0.596134   3.0 -0.418035  0.883386 -1.251459 -0.881060
b     1.083899  1.666605   2.0 -0.162902  1.093030 -0.935791 -0.549346


           50%       75%       max
key1
a    -0.510661 -0.001324  0.508013
b    -0.162902  0.223543  0.609987

[2 rows x 24 columns]

### 10.2.1 Column-Wise and Multiple Function Application

In [52]:
tips = pd.read_csv("examples/tips.csv")

In [53]:
tips.head(10)

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4
5       25.29  4.71     No  Sun  Dinner     4
6        8.77  2.00     No  Sun  Dinner     2
7       26.88  3.12     No  Sun  Dinner     4
8       15.04  1.96     No  Sun  Dinner     2
9       14.78  3.23     No  Sun  Dinner     2

In [54]:
tips["tip_pct"] = tips["tip"] / tips["total_bill"]

In [55]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [56]:
grouped = tips.groupby(["day", "smoker"])

In [57]:
grouped_pct = grouped["tip_pct"]

In [58]:
grouped_pct.agg("mean")

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [59]:
grouped_pct.agg(["mean", "std", peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [60]:
grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\1734782830.py:1: FutureWarning: The provided callable <function std at 0x0000023A87C01260> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.028123
     Yes     0.174783  0.051293
Sat  No      0.158048  0.039767
     Yes     0.147906  0.061375
Sun  No      0.160113  0.042347
     Yes     0.187250  0.154134
Thur No      0.160298  0.038774
     Yes     0.163863  0.039389

In [61]:
functions = ["count", "mean", "max"]

In [62]:
result = grouped[["tip_pct", "total_bill"]].agg(functions)

In [63]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [64]:
result["tip_pct"]

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [65]:
ftuples = [("Average", "mean"), ("Variables", np.var)]

In [66]:
grouped[["tip_pct", "total_bill"]].agg(ftuples)

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\365474927.py:1: FutureWarning: The provided callable <function var at 0x0000023A87C013A0> is currently using SeriesGroupBy.var. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "var" instead.
  grouped[["tip_pct", "total_bill"]].agg(ftuples)

              tip_pct           total_bill
              Average Variables    Average   Variables
day  smoker
Fri  No      0.151650  0.000791  18.420000   25.596333
     Yes     0.174783  0.002631  16.813333   82.562438
Sat  No      0.158048  0.001581  19.661778   79.908965
     Yes     0.147906  0.003767  21.276667  101.387535
Sun  No      0.160113  0.001793  20.506667   66.099980
     Yes     0.187250  0.023757  24.120000  109.046044
Thur No      0.160298  0.001503  17.113111   59.625081
     Yes     0.163863  0.001551  19.190588   69.808518

In [67]:
grouped.agg({"tip": np.max, "size": "sum"})

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\3453032214.py:1: FutureWarning: The provided callable <function max at 0x0000023A87C00720> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grouped.agg({"tip": np.max, "size": "sum"})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [68]:
grouped.agg({"tip_pct": ["min", "max", "mean", "std"], 
             "size": "sum"})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [71]:
tips.groupby(["day", "smoker"], as_index=False).mean(numeric_only = True)

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863

In [74]:
def top(df, n=5, column="tip_pct"):
    return df.sort_values(column, ascending = False)[:n]

In [75]:
top(tips, n=6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [76]:
tips.groupby("smoker").apply(top)

C:\Users\34327\AppData\Local\Temp\ipykernel_6952\2530541573.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker").apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     232       11.61  3.39     No   Sat  Dinner     2  0.291990
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       88        24.71  5.85     No  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       109       14.31  4.00    Yes   Sat  Dinner     2  0.279525