In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import re

In [4]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [8]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [9]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [10]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [11]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], 
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [16]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = np.nan

In [20]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis="columns", how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [23]:
df

          0         1         2
0 -0.198060  0.743392  0.656453
1  0.153916  0.777746  3.498713
2 -0.912118 -0.102151  1.181909
3 -1.268878 -0.503161 -0.058997
4 -0.379949  0.241807 -0.107805
5  0.026822 -1.658601 -2.167842
6  0.494079 -0.507776 -0.646137

In [24]:
df.iloc[:4, 1] = np.nan

In [25]:
df

          0         1         2
0 -0.198060       NaN  0.656453
1  0.153916       NaN  3.498713
2 -0.912118       NaN  1.181909
3 -1.268878       NaN -0.058997
4 -0.379949  0.241807 -0.107805
5  0.026822 -1.658601 -2.167842
6  0.494079 -0.507776 -0.646137

In [26]:
df.iloc[:2, 2] = np.nan

In [27]:
df

          0         1         2
0 -0.198060       NaN       NaN
1  0.153916       NaN       NaN
2 -0.912118       NaN  1.181909
3 -1.268878       NaN -0.058997
4 -0.379949  0.241807 -0.107805
5  0.026822 -1.658601 -2.167842
6  0.494079 -0.507776 -0.646137

In [28]:
df.dropna()

          0         1         2
4 -0.379949  0.241807 -0.107805
5  0.026822 -1.658601 -2.167842
6  0.494079 -0.507776 -0.646137

In [29]:
df.dropna(thresh=2)

          0         1         2
2 -0.912118       NaN  1.181909
3 -1.268878       NaN -0.058997
4 -0.379949  0.241807 -0.107805
5  0.026822 -1.658601 -2.167842
6  0.494079 -0.507776 -0.646137

In [30]:
df.fillna(0)

          0         1         2
0 -0.198060  0.000000  0.000000
1  0.153916  0.000000  0.000000
2 -0.912118  0.000000  1.181909
3 -1.268878  0.000000 -0.058997
4 -0.379949  0.241807 -0.107805
5  0.026822 -1.658601 -2.167842
6  0.494079 -0.507776 -0.646137

In [31]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.198060  0.500000  0.000000
1  0.153916  0.500000  0.000000
2 -0.912118  0.500000  1.181909
3 -1.268878  0.500000 -0.058997
4 -0.379949  0.241807 -0.107805
5  0.026822 -1.658601 -2.167842
6  0.494079 -0.507776 -0.646137

In [32]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [33]:
df

          0         1         2
0 -0.291698  1.602496 -0.870151
1 -0.183141  0.798061 -0.203679
2 -0.600485 -0.674095 -0.310204
3  0.865554 -1.049412 -0.823218
4 -0.805550  0.469250 -0.072036
5 -2.410537 -1.349845  1.084251

In [34]:
df.iloc[2:, 1] = np.nan

In [35]:
df.iloc[4:, 2] = np.nan

In [36]:
df

          0         1         2
0 -0.291698  1.602496 -0.870151
1 -0.183141  0.798061 -0.203679
2 -0.600485       NaN -0.310204
3  0.865554       NaN -0.823218
4 -0.805550       NaN       NaN
5 -2.410537       NaN       NaN

In [37]:
df.fillna(method = "ffill")

C:\Users\34327\AppData\Local\Temp\ipykernel_3404\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

          0         1         2
0 -0.291698  1.602496 -0.870151
1 -0.183141  0.798061 -0.203679
2 -0.600485  0.798061 -0.310204
3  0.865554  0.798061 -0.823218
4 -0.805550  0.798061 -0.823218
5 -2.410537  0.798061 -0.823218

In [38]:
df.fillna(method = "ffill", limit = 2)

C:\Users\34327\AppData\Local\Temp\ipykernel_3404\1904396064.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill", limit = 2)

          0         1         2
0 -0.291698  1.602496 -0.870151
1 -0.183141  0.798061 -0.203679
2 -0.600485  0.798061 -0.310204
3  0.865554  0.798061 -0.823218
4 -0.805550       NaN -0.823218
5 -2.410537       NaN -0.823218

In [39]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [40]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [41]:
data = pd.DataFrame({"k1":["one", "two"]*3+["two"], 
                    "k2":[1, 1, 2, 3, 3, 4, 4]})

In [42]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [43]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [44]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [45]:
data["v1"] = range(7)

In [46]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [47]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [48]:
data.drop_duplicates(["k1","k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [49]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", 
                             "pastrami", "corned beef", "bacon", 
                             "pastrami", "honey ham", "nova lox"], 
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6, ]})

In [50]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [51]:
meat_to_animal = {
    "bacon": "pig", 
    "pulled pork": "pig", 
    "pastrami": "cow", 
    "corned beef": "cow", 
    "honey ham": "pig", 
    "nova lox": "salmon"
}

In [52]:
data["animal"] = data["food"].map(meat_to_animal)

In [53]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [54]:
def get_animal(x):
    return meat_to_animal[x]

In [55]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [56]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [57]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [59]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [60]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [61]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [62]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                    index=["Ohio", "Colorado", "New York"], 
                    columns=["one", "two", "three", "four"])

In [63]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [64]:
def transform(x):
    return x[:4].upper()

In [65]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [66]:
data.index = data.index.map(transform)

In [67]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [68]:
data.rename(index = str.title, columns = str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [69]:
data.rename(index = {"OHIO": "INDIANA"}, 
           columns = {"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [70]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [71]:
bins = [18, 25, 35, 60, 100]

In [72]:
age_categories = pd.cut(ages, bins)

In [73]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [74]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [75]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [76]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [77]:
pd.value_counts(age_categories)

C:\Users\34327\AppData\Local\Temp\ipykernel_3404\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [78]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [79]:
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [80]:
data = np.random.uniform(size = 20)

In [81]:
pd.cut(data, 4, precision = 2)

[(0.75, 0.98], (0.3, 0.52], (0.3, 0.52], (0.3, 0.52], (0.3, 0.52], ..., (0.069, 0.3], (0.3, 0.52], (0.52, 0.75], (0.3, 0.52], (0.75, 0.98]]
Length: 20
Categories (4, interval[float64, right]): [(0.069, 0.3] < (0.3, 0.52] < (0.52, 0.75] < (0.75, 0.98]]

In [82]:
pd.value_counts(data)

C:\Users\34327\AppData\Local\Temp\ipykernel_3404\3657943749.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data)

0.805424    1
0.333170    1
0.424175    1
0.588342    1
0.465228    1
0.070075    1
0.587722    1
0.652219    1
0.189053    1
0.372803    1
0.916530    1
0.516099    1
0.259932    1
0.978882    1
0.122198    1
0.389797    1
0.414627    1
0.474439    1
0.469272    1
0.871336    1
Name: count, dtype: int64

In [83]:
data = np.random.standard_normal(1000)

In [84]:
quartiles = pd.qcut(data, 4, precision = 2)

In [85]:
quartiles

[(0.02, 0.63], (0.02, 0.63], (-2.78, -0.68], (-2.78, -0.68], (-2.78, -0.68], ..., (-0.68, 0.02], (-0.68, 0.02], (-0.68, 0.02], (-0.68, 0.02], (-0.68, 0.02]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.78, -0.68] < (-0.68, 0.02] < (0.02, 0.63] < (0.63, 3.24]]

In [86]:
pd.value_counts(quartiles)

C:\Users\34327\AppData\Local\Temp\ipykernel_3404\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)

(-2.78, -0.68]    250
(-0.68, 0.02]     250
(0.02, 0.63]      250
(0.63, 3.24]      250
Name: count, dtype: int64

In [87]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.776, -1.284]    100
(-1.284, 0.0204]    400
(0.0204, 1.275]     400
(1.275, 3.243]      100
Name: count, dtype: int64

In [88]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [89]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.010325    -0.007782     0.001564     0.048943
std       1.042949     0.971496     1.017520     0.999989
min      -4.134702    -3.498858    -3.229013    -3.651343
25%      -0.716006    -0.661948    -0.670695    -0.636545
50%      -0.003831     0.023484     0.006729     0.017425
75%       0.661197     0.604312     0.716274     0.730194
max       2.978634     2.908059     3.484874     3.806365

In [90]:
col = data[2]

In [91]:
col[col.abs() > 3]

183    3.484874
832   -3.229013
Name: 2, dtype: float64

In [92]:
data[(data.abs() > 3).any(axis = "columns")]

            0         1         2         3
53   0.457830  0.231857  2.212665  3.001471
74  -3.050315 -0.289000 -0.010673 -0.883936
183  0.859450 -1.077115  3.484874  0.266448
193 -0.248868  0.538652  0.307858  3.806365
227 -1.657783 -3.498858 -2.287236 -0.627663
334 -3.494562  1.517172 -0.080022  1.044211
352  1.255153  1.989375  0.790506  3.062215
741 -4.134702  0.002924  1.493860  0.666320
832 -1.887112 -1.186053 -3.229013 -0.689112
920  0.369189 -0.801931 -1.234061 -3.651343

In [93]:
data[data.abs() > 3] = np.sign(data) * 3

In [94]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.008645    -0.007283     0.001308     0.048724
std       1.037377     0.969829     1.015269     0.994878
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.716006    -0.661948    -0.670695    -0.636545
50%      -0.003831     0.023484     0.006729     0.017425
75%       0.661197     0.604312     0.716274     0.730194
max       2.978634     2.908059     3.000000     3.000000

In [95]:
np.sign(data).head()

     0    1    2    3
0  1.0  1.0 -1.0 -1.0
1  1.0 -1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0  1.0  1.0 -1.0
4 -1.0 -1.0  1.0  1.0

In [96]:
np.sign(data).tail()

       0    1    2    3
995  1.0  1.0 -1.0 -1.0
996 -1.0 -1.0 -1.0 -1.0
997 -1.0 -1.0 -1.0  1.0
998 -1.0 -1.0 -1.0 -1.0
999 -1.0 -1.0 -1.0  1.0

In [97]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [98]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [99]:
sampler = np.random.permutation(5)

In [100]:
sampler

array([2, 0, 4, 3, 1], dtype=int32)

In [101]:
df.take(sampler)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13

In [102]:
df.iloc[sampler]

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13

In [103]:
column_sampler = np.random.permutation(7)

In [104]:
column_sampler

array([5, 0, 1, 3, 2, 4, 6], dtype=int32)

In [105]:
df.take(column_sampler, axis = "columns")

    5   0   1   3   2   4   6
0   5   0   1   3   2   4   6
1  12   7   8  10   9  11  13
2  19  14  15  17  16  18  20
3  26  21  22  24  23  25  27
4  33  28  29  31  30  32  34

In [106]:
df.sample(n=3)

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [107]:
choices = pd.Series([5, 7, -1, 6, 4])

In [108]:
choices.sample(n = 10, replace = True)

1    7
1    7
2   -1
0    5
0    5
1    7
0    5
3    6
1    7
4    4
dtype: int64

In [109]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], 
                  "data1": range(6)})

In [110]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [111]:
pd.get_dummies(df["key"], dtype=int)

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [112]:
dummies = pd.get_dummies(df["key"], prefix = "key", dtype=int)

In [113]:
df_with_dummy = df[["data1"]].join(dummies)

In [114]:
df_with_dummy

   data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [115]:
mnames = ["movie_id", "title", "genres"]

In [116]:
movies = pd.read_table("datasets/movielens/movies.dat", sep="::", 
                      header=None, names=mnames, engine="python")

In [117]:
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [118]:
dummies = movies["genres"].str.get_dummies("|")

In [119]:
dummies.iloc[:10,:6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [120]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [121]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

In [122]:
np.random.seed(12345) #为了使示例数据是重复的

In [123]:
values = np.random.uniform(size = 10)

In [124]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [125]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [126]:
pd.get_dummies(pd.cut(values, bins), dtype="int32")

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

7.4.1 python buit-in string object methods

In [127]:
val = "a,b,   guido"

In [128]:
val.split(",")

['a', 'b', '   guido']

In [129]:
pieces = [x.strip() for x in val.split(",")]

In [130]:
pieces

['a', 'b', 'guido']

In [131]:
first, second, third = pieces

In [132]:
first + "::" + second + "::" + third

'a::b::guido'

In [133]:
"::".join(pieces)

'a::b::guido'

In [134]:
"guido" in val

True

In [135]:
val.index(",")

1

In [136]:
val.find(":")

-1

In [137]:
val.count(",")

2

In [138]:
val.replace(",", "::")

'a::b::   guido'

In [139]:
val.replace(",","")

'ab   guido'

In [140]:
text = "foo    bar\t baz  \tqux"

In [141]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [142]:
regex = re.compile(r"\s+")

In [143]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [144]:
regex.findall(text)

['    ', '\t ', '  \t']

In [145]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

In [146]:
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [147]:
# re.IGNORECASE 使正则表达式不区分大小写
regex = re.compile(pattern, flags=re.IGNORECASE)

In [148]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [149]:
m = regex.search(text)

In [150]:
m

In [151]:
text[m.start():m.end()]

'dave@google.com'

In [152]:
print(regex.match(text))

None

In [153]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [154]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [155]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [156]:
m = regex.match("wesm@bright.net")

In [157]:
m.groups()

('wesm', 'bright', 'net')

In [158]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [159]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

## 7.4 String Functions in pandas

In [160]:
data = {"Dave": "dave@google.com", 
        "Steve": "steve@gmail.com", 
        "Rob": "rob@gmail.com", 
        "Wes": np.nan}

In [161]:
data = pd.Series(data)

In [162]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [163]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [164]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [165]:
data_as_string_ext = data.astype('string')

In [166]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [167]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [175]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

#对邮箱里的 用户名、域名 和 后缀 这三个部分感兴趣

In [169]:
data.str.findall(pattern, flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [171]:
matches = data.str.findall(pattern, flags = re.IGNORECASE).str[0]

In [172]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [173]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [176]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [177]:
data.str.extract(pattern, flags = re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN