In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [7]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [12]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [13]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], 
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [15]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [17]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data[4] = np.nan

In [19]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [20]:
data.dropna(axis="columns", how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [25]:
df

          0         1         2
0  0.046788  0.311894 -2.027795
1  0.207606  0.108942 -0.137657
2  0.442463  2.246282 -0.499526
3  0.691320 -0.241258  0.167597
4 -2.251329  0.601042 -1.059212
5 -1.027956 -0.349769 -0.574443
6 -0.418619  0.366573 -0.528133

In [26]:
df.iloc[:4, 1] = np.nan

In [27]:
df

          0         1         2
0  0.046788       NaN -2.027795
1  0.207606       NaN -0.137657
2  0.442463       NaN -0.499526
3  0.691320       NaN  0.167597
4 -2.251329  0.601042 -1.059212
5 -1.027956 -0.349769 -0.574443
6 -0.418619  0.366573 -0.528133

In [28]:
df.iloc[:2, 2] = np.nan

In [29]:
df

          0         1         2
0  0.046788       NaN       NaN
1  0.207606       NaN       NaN
2  0.442463       NaN -0.499526
3  0.691320       NaN  0.167597
4 -2.251329  0.601042 -1.059212
5 -1.027956 -0.349769 -0.574443
6 -0.418619  0.366573 -0.528133

In [30]:
df.dropna()

          0         1         2
4 -2.251329  0.601042 -1.059212
5 -1.027956 -0.349769 -0.574443
6 -0.418619  0.366573 -0.528133

In [31]:
df.dropna(thresh=2)

          0         1         2
2  0.442463       NaN -0.499526
3  0.691320       NaN  0.167597
4 -2.251329  0.601042 -1.059212
5 -1.027956 -0.349769 -0.574443
6 -0.418619  0.366573 -0.528133

In [32]:
df.fillna(0)

          0         1         2
0  0.046788  0.000000  0.000000
1  0.207606  0.000000  0.000000
2  0.442463  0.000000 -0.499526
3  0.691320  0.000000  0.167597
4 -2.251329  0.601042 -1.059212
5 -1.027956 -0.349769 -0.574443
6 -0.418619  0.366573 -0.528133

In [33]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  0.046788  0.500000  0.000000
1  0.207606  0.500000  0.000000
2  0.442463  0.500000 -0.499526
3  0.691320  0.500000  0.167597
4 -2.251329  0.601042 -1.059212
5 -1.027956 -0.349769 -0.574443
6 -0.418619  0.366573 -0.528133

In [34]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [35]:
df

          0         1         2
0 -0.310395 -1.017215 -1.286281
1  0.532091  0.669713  0.137199
2 -0.217129 -0.674641  0.598172
3 -0.943714 -0.519497 -1.566275
4  1.308973 -1.334489  0.047700
5  0.926951  0.918010  0.872708

In [36]:
df.iloc[2:, 1] = np.nan

In [37]:
df.iloc[4:, 2] = np.nan

In [38]:
df

          0         1         2
0 -0.310395 -1.017215 -1.286281
1  0.532091  0.669713  0.137199
2 -0.217129       NaN  0.598172
3 -0.943714       NaN -1.566275
4  1.308973       NaN       NaN
5  0.926951       NaN       NaN

In [39]:
df.fillna(method = "ffill")

C:\Users\34327\AppData\Local\Temp\ipykernel_9572\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

          0         1         2
0 -0.310395 -1.017215 -1.286281
1  0.532091  0.669713  0.137199
2 -0.217129  0.669713  0.598172
3 -0.943714  0.669713 -1.566275
4  1.308973  0.669713 -1.566275
5  0.926951  0.669713 -1.566275

In [40]:
df.fillna(method = "ffill", limit = 2)

C:\Users\34327\AppData\Local\Temp\ipykernel_9572\1904396064.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill", limit = 2)

          0         1         2
0 -0.310395 -1.017215 -1.286281
1  0.532091  0.669713  0.137199
2 -0.217129  0.669713  0.598172
3 -0.943714  0.669713 -1.566275
4  1.308973       NaN -1.566275
5  0.926951       NaN -1.566275

In [41]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [42]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64