In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [7]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [12]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [13]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], 
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [15]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [17]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data[4] = np.nan

In [19]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [20]:
data.dropna(axis="columns", how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [21]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [22]:
df

          0         1         2
0 -0.508224 -0.048545 -0.151555
1  0.218319  2.005056  0.218551
2 -0.271864  0.371850  0.329346
3 -0.154330  0.599561  0.159224
4 -0.766111  0.850503  0.151743
5  1.193744  1.149893 -0.864124
6 -0.830587 -0.332726  2.127847

In [23]:
df.iloc[:4, 1] = np.nan

In [24]:
df

          0         1         2
0 -0.508224       NaN -0.151555
1  0.218319       NaN  0.218551
2 -0.271864       NaN  0.329346
3 -0.154330       NaN  0.159224
4 -0.766111  0.850503  0.151743
5  1.193744  1.149893 -0.864124
6 -0.830587 -0.332726  2.127847

In [25]:
df.iloc[:2, 2] = np.nan

In [26]:
df

          0         1         2
0 -0.508224       NaN       NaN
1  0.218319       NaN       NaN
2 -0.271864       NaN  0.329346
3 -0.154330       NaN  0.159224
4 -0.766111  0.850503  0.151743
5  1.193744  1.149893 -0.864124
6 -0.830587 -0.332726  2.127847

In [27]:
df.dropna()

          0         1         2
4 -0.766111  0.850503  0.151743
5  1.193744  1.149893 -0.864124
6 -0.830587 -0.332726  2.127847

In [28]:
df.dropna(thresh=2)

          0         1         2
2 -0.271864       NaN  0.329346
3 -0.154330       NaN  0.159224
4 -0.766111  0.850503  0.151743
5  1.193744  1.149893 -0.864124
6 -0.830587 -0.332726  2.127847

In [29]:
df.fillna(0)

          0         1         2
0 -0.508224  0.000000  0.000000
1  0.218319  0.000000  0.000000
2 -0.271864  0.000000  0.329346
3 -0.154330  0.000000  0.159224
4 -0.766111  0.850503  0.151743
5  1.193744  1.149893 -0.864124
6 -0.830587 -0.332726  2.127847

In [30]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.508224  0.500000  0.000000
1  0.218319  0.500000  0.000000
2 -0.271864  0.500000  0.329346
3 -0.154330  0.500000  0.159224
4 -0.766111  0.850503  0.151743
5  1.193744  1.149893 -0.864124
6 -0.830587 -0.332726  2.127847

In [31]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [32]:
df

          0         1         2
0  1.044570 -0.177603 -0.840590
1 -1.359288  0.681887  1.961348
2 -1.365645 -1.040684 -1.057831
3  0.735551  1.371203 -1.538375
4 -0.050970 -0.380540 -0.889948
5  0.042575 -0.908075 -1.315551

In [33]:
df.iloc[2:, 1] = np.nan

In [34]:
df.iloc[4:, 2] = np.nan

In [35]:
df

          0         1         2
0  1.044570 -0.177603 -0.840590
1 -1.359288  0.681887  1.961348
2 -1.365645       NaN -1.057831
3  0.735551       NaN -1.538375
4 -0.050970       NaN       NaN
5  0.042575       NaN       NaN

In [36]:
df.fillna(method = "ffill")

C:\Users\34327\AppData\Local\Temp\ipykernel_12240\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

          0         1         2
0  1.044570 -0.177603 -0.840590
1 -1.359288  0.681887  1.961348
2 -1.365645  0.681887 -1.057831
3  0.735551  0.681887 -1.538375
4 -0.050970  0.681887 -1.538375
5  0.042575  0.681887 -1.538375

In [37]:
df.fillna(method = "ffill", limit = 2)

C:\Users\34327\AppData\Local\Temp\ipykernel_12240\1904396064.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill", limit = 2)

          0         1         2
0  1.044570 -0.177603 -0.840590
1 -1.359288  0.681887  1.961348
2 -1.365645  0.681887 -1.057831
3  0.735551  0.681887 -1.538375
4 -0.050970       NaN -1.538375
5  0.042575       NaN -1.538375

In [38]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [39]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [40]:
data = pd.DataFrame({"k1":["one", "two"]*3+["two"], 
                    "k2":[1, 1, 2, 3, 3, 4, 4]})

In [41]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [42]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [43]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [44]:
data["v1"] = range(7)

In [45]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [46]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [47]:
data.drop_duplicates(["k1","k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [48]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", 
                             "pastrami", "corned beef", "bacon", 
                             "pastrami", "honey ham", "nova lox"], 
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6, ]})

In [49]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [50]:
meat_to_animal = {
    "bacon": "pig", 
    "pulled pork": "pig", 
    "pastrami": "cow", 
    "corned beef": "cow", 
    "honey ham": "pig", 
    "nova lox": "salmon"
}

In [51]:
data["animal"] = data["food"].map(meat_to_animal)

In [52]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [53]:
def get_animal(x):
    return meat_to_animal[x]

In [54]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [55]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [56]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [59]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [61]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                    index=["Ohio", "Colorado", "New York"], 
                    columns=["one", "two", "three", "four"])

In [62]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [63]:
def transform(x):
    return x[:4].upper()

In [64]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [65]:
data.index = data.index.map(transform)

In [66]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [67]:
data.rename(index = str.title, columns = str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [68]:
data.rename(index = {"OHIO": "INDIANA"}, 
           columns = {"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [69]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [70]:
bins = [18, 25, 35, 60, 100]

In [71]:
age_categories = pd.cut(ages, bins)

In [72]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [73]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [74]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [75]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [76]:
pd.value_counts(age_categories)

C:\Users\34327\AppData\Local\Temp\ipykernel_12240\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [77]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [78]:
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [79]:
data = np.random.uniform(size = 20)

In [80]:
pd.cut(data, 4, precision = 2)

[(0.26, 0.48], (0.033, 0.26], (0.033, 0.26], (0.033, 0.26], (0.26, 0.48], ..., (0.033, 0.26], (0.71, 0.93], (0.71, 0.93], (0.26, 0.48], (0.26, 0.48]]
Length: 20
Categories (4, interval[float64, right]): [(0.033, 0.26] < (0.26, 0.48] < (0.48, 0.71] < (0.71, 0.93]]

In [81]:
pd.value_counts(data)

C:\Users\34327\AppData\Local\Temp\ipykernel_12240\3657943749.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data)

0.354676    1
0.196472    1
0.267814    1
0.912122    1
0.803939    1
0.230673    1
0.931722    1
0.034118    1
0.597169    1
0.891057    1
0.313336    1
0.472586    1
0.219764    1
0.356449    1
0.116582    1
0.344562    1
0.442410    1
0.088330    1
0.074936    1
0.356321    1
Name: count, dtype: int64

In [82]:
data = np.random.standard_normal(1000)

In [83]:
quartiles = pd.qcut(data, 4, precision = 2)

In [84]:
quartiles

[(0.68, 3.44], (0.008, 0.68], (-0.63, 0.008], (-0.63, 0.008], (0.68, 3.44], ..., (0.008, 0.68], (-3.69, -0.63], (0.008, 0.68], (0.008, 0.68], (-0.63, 0.008]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.69, -0.63] < (-0.63, 0.008] < (0.008, 0.68] < (0.68, 3.44]]

In [85]:
pd.value_counts(quartiles)

C:\Users\34327\AppData\Local\Temp\ipykernel_12240\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)

(-3.69, -0.63]    250
(-0.63, 0.008]    250
(0.008, 0.68]     250
(0.68, 3.44]      250
Name: count, dtype: int64

In [86]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.685, -1.208]     100
(-1.208, 0.00799]    400
(0.00799, 1.35]      400
(1.35, 3.443]        100
Name: count, dtype: int64

In [87]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [88]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.023900     0.077194     0.012538    -0.001252
std       1.028460     0.984008     0.970387     1.008468
min      -3.228031    -3.318004    -3.044685    -3.456928
25%      -0.767030    -0.541422    -0.615778    -0.704039
50%      -0.049597     0.083871    -0.005425    -0.018385
75%       0.656549     0.761324     0.643808     0.685574
max       3.234713     3.116647     3.116881     3.271531

In [89]:
col = data[2]

In [90]:
col[col.abs() > 3]

437   -3.044685
438    3.116881
447    3.096789
Name: 2, dtype: float64

In [91]:
data[(data.abs() > 3).any(axis = "columns")]

            0         1         2         3
18   0.234163  1.167352  0.161698 -3.456928
36   2.021616  3.116647  0.045163 -0.304137
200 -0.651327  0.872297  1.826159 -3.429340
218  1.165399  0.003899 -0.957350 -3.101398
437 -0.453275  0.695989 -3.044685 -0.709238
438 -0.695357  0.349632  3.116881 -0.014610
447 -0.320985 -1.393024  3.096789 -0.487257
499 -0.658379 -3.318004  0.010359 -0.764617
571 -0.653076  1.523507  0.560915 -3.115011
813  2.404612  3.016999  0.794680 -0.096893
868 -0.098885  0.504219 -0.168728  3.271531
892 -3.228031  1.480042  0.184431 -1.272616
934  3.234713 -2.063522 -0.382188  0.583568

In [92]:
data[data.abs() > 3] = np.sign(data) * 3

In [93]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.023907     0.077378     0.012369    -0.000421
std       1.027056     0.982555     0.969576     1.004124
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.767030    -0.541422    -0.615778    -0.704039
50%      -0.049597     0.083871    -0.005425    -0.018385
75%       0.656549     0.761324     0.643808     0.685574
max       3.000000     3.000000     3.000000     3.000000

In [94]:
np.sign(data).head()

     0    1    2    3
0  1.0 -1.0  1.0  1.0
1  1.0 -1.0 -1.0  1.0
2  1.0  1.0  1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4  1.0 -1.0 -1.0  1.0

In [95]:
np.sign(data).tail()

       0    1    2    3
995  1.0 -1.0  1.0  1.0
996  1.0  1.0  1.0  1.0
997 -1.0  1.0 -1.0 -1.0
998  1.0 -1.0  1.0  1.0
999 -1.0 -1.0 -1.0  1.0

In [96]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [97]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [98]:
sampler = np.random.permutation(5)

In [99]:
sampler

array([1, 0, 2, 4, 3], dtype=int32)

In [100]:
df.take(sampler)

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [101]:
df.iloc[sampler]

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [102]:
column_sampler = np.random.permutation(7)

In [103]:
column_sampler

array([5, 4, 0, 6, 1, 2, 3], dtype=int32)

In [104]:
df.take(column_sampler, axis = "columns")

    5   4   0   6   1   2   3
0   5   4   0   6   1   2   3
1  12  11   7  13   8   9  10
2  19  18  14  20  15  16  17
3  26  25  21  27  22  23  24
4  33  32  28  34  29  30  31

In [105]:
df.sample(n=3)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27

In [106]:
choices = pd.Series([5, 7, -1, 6, 4])

In [107]:
choices.sample(n = 10, replace = True)

2   -1
4    4
3    6
1    7
3    6
0    5
2   -1
4    4
1    7
3    6
dtype: int64

In [108]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], 
                  "data1": range(6)})

In [109]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [110]:
pd.get_dummies(df["key"], dtype=int)

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [111]:
dummies = pd.get_dummies(df["key"], prefix = "key", dtype=int)

In [112]:
df_with_dummy = df[["data1"]].join(dummies)

In [113]:
df_with_dummy

   data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [114]:
mnames = ["movie_id", "title", "genres"]

In [115]:
movies = pd.read_table("datasets/movielens/movies.dat", sep="::", 
                      header=None, names=mnames, engine="python")

In [116]:
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [117]:
dummies = movies["genres"].str.get_dummies("|")

In [120]:
dummies.iloc[:10,:6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [121]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [123]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

In [125]:
np.random.seed(12345) #为了使示例数据是重复的

In [126]:
values = np.random.uniform(size = 10)

In [127]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [128]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [130]:
pd.get_dummies(pd.cut(values, bins), dtype="int32")

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0