In [1]:
import numpy as np
import pandas as pd

data = np.arange(9)
print(data)

[0 1 2 3 4 5 6 7 8]

In [2]:
data = data.reshape((3,3))

In [3]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
frame = pd.DataFrame(data)

In [5]:
frame

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [6]:
frame = pd.DataFrame(data,
                    index = ["a", "c", "d"],
                    columns = ["Ohio", "Texas", "California"])

In [7]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [8]:
obj = pd.Series(np.arange(4.), index = ["a", "b", "c", "d"])

In [9]:
obj.loc["b"] # 按标签：1.0

np.float64(1.0)

In [10]:
obj.iloc[1] # 按位置：1.0

np.float64(1.0)

In [11]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [12]:
obj1

2    1
0    2
1    3
dtype: int64

In [13]:
obj1.loc[0]     # 标签"0"对应的值 → 2

np.int64(2)

In [14]:
obj1.iloc[0]    # 第0个位置的值 → 1

np.int64(1)

In [15]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                   index = ["Ohio", "Colorado", "Utah", "New York"], 
                   columns = ["one", "two", "three", "four"])

In [16]:
data[data < 5] = 0

In [17]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [18]:
data["two"] #取一列 -> Sereies

Ohio         0
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [19]:
data[["one", "two"]] #取多列 -> DataFrame

          one  two
Ohio        0    0
Colorado    0    5
Utah        8    9
New York   12   13

In [20]:
data.loc[:, "two"] #取two列

Ohio         0
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [21]:
data.loc[:, ["one", "two"]] # 取one列和two列

          one  two
Ohio        0    0
Colorado    0    5
Utah        8    9
New York   12   13

In [22]:
data.loc["Colorado":"Utah", "two":"three"]

          two  three
Colorado    5      6
Utah        9     10

In [23]:
data.iloc[0] #取第0行 -> Ohio哪一行

one      0
two      0
three    0
four     0
Name: Ohio, dtype: int64

In [24]:
data.iloc[1:3] # 取第1到2行（不含第三行）

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11

In [25]:
data.iloc[:, 0] #第0列 -> one

Ohio         0
Colorado     0
Utah         8
New York    12
Name: one, dtype: int64

In [26]:
data.iloc[:, 1:3] #取第1到2列，不包含第3列 -> two, three

          two  three
Ohio        0      0
Colorado    5      6
Utah        9     10
New York   13     14

In [27]:
data.iloc[1:3,1:3]

          two  three
Colorado    5      6
Utah        9     10

In [28]:
data.at["Utah", "three"]

np.int64(10)

In [29]:
data.iat[2,2]

np.int64(10)