In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from pandas import Series, DataFrame

In [4]:
obj = pd.Series([4, 7, -5, 3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2["a"]

np.int64(-5)

In [12]:
obj2["d"] = 6

In [13]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
"b" in obj2

True

In [18]:
"e" in obj2

False

In [19]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [23]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [24]:
obj4 = pd.Series(sdata, index = states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name = "population" #给Series本身命名为 "population"

In [33]:
obj4.index.name = "state" #给索引（index）起名叫 "state"

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [36]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [38]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [39]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [41]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [42]:
pd.DataFrame(data, columns = ["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [43]:
frame2 = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])

In [44]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [47]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [48]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [49]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [50]:
frame2["debt"] = 16.5

In [51]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [52]:
frame2["debt"] = np.arange(6.)

In [53]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [54]:
val = pd.Series([-1.2, -1.5, -1.7], index = ["two", "four", "five"])

In [55]:
frame2["debt"] = val

In [56]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [57]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [58]:
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [59]:
del frame2["eastern"]

In [60]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [61]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}

In [62]:
frame3 = pd.DataFrame(populations)

In [63]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [64]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [65]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [66]:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}

In [67]:
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [68]:
frame3.index.name = "year"

In [69]:
frame3.columns.name = "state"

In [70]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [71]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [72]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [73]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [74]:
index = obj.index

In [75]:
index

Index(['a', 'b', 'c'], dtype='object')

In [76]:
index[1:]

Index(['b', 'c'], dtype='object')

In [77]:
labels = pd.Index(np.arange(3))

In [78]:
labels

Index([0, 1, 2], dtype='int64')

In [79]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [80]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [81]:
obj2.index is labels

True

In [82]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [83]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [84]:
"Ohio" in frame3.columns

True

In [85]:
2003 in frame3.columns

False

In [86]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [87]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ["d", "b", "a", "c"])

In [88]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [89]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [90]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [91]:
obj3 = pd.Series(["blue", "purple", "yellow"], index = [0, 2, 4])

In [92]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [93]:
obj3.reindex(np.arange(6), method = "ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [94]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index = ["a", "c", "d"],  #给每一行取名字
                    columns=["Ohio", "Texas", "California"]) #给每一列取名字

In [95]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [96]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])

In [97]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [98]:
states = ["Texas", "Utah", "California"]

In [99]:
frame.reindex(columns = states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [100]:
frame.reindex(states, axis = "columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [101]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

In [102]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [103]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [104]:
new_obj = obj.drop("c")

In [105]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [106]:
obj.drop({"b", "c"})

a    0.0
d    3.0
e    4.0
dtype: float64

In [107]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index = ["Ohio", "Colorado", "Utah", "New York"], 
                   columns = ["one", "two", "three", "four"])

In [108]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [109]:
data.drop(index = ["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
data.drop(columns = ["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [111]:
data.drop("two", axis = 1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [112]:
data.drop(["two", "four"], axis = "columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [113]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [114]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [115]:
obj["b"]

np.float64(1.0)

In [116]:
obj[1]

C:\Users\34327\AppData\Local\Temp\ipykernel_17260\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [117]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [118]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [119]:
obj[[1, 3]]

C:\Users\34327\AppData\Local\Temp\ipykernel_17260\2982346117.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [120]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [121]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [122]:
obj1 = pd.Series([1, 2, 3], index = [2, 0, 1])

In [123]:
obj2 = pd.Series([1, 2, 3], index = ["a", "b", "c"])

In [124]:
obj1

2    1
0    2
1    3
dtype: int64

In [125]:
obj2

a    1
b    2
c    3
dtype: int64

In [126]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [127]:
obj2[[0, 1, 2]]

C:\Users\34327\AppData\Local\Temp\ipykernel_17260\2599987575.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [128]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [129]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [130]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [131]:
obj2.loc["b":"c"] = 5

In [132]:
obj2

a    1
b    5
c    5
dtype: int64

In [133]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                   index = ["Ohio", "Colorado", "Utah", "New York"], 
                   columns = ["one", "two", "three", "four"])

In [134]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [136]:
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [137]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [138]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [139]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [140]:
data[data < 5] = 0

In [141]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [143]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [144]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [145]:
data.iloc[2] #第三行的内容

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [146]:
data.iloc[[2, 1]] #第三行，第二行

          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [147]:
data.iloc[2, [3, 0, 1]] #第三行的第四列、一列、二列

four    11
one      8
two      9
Name: Utah, dtype: int64

In [148]:
data.iloc[[1, 2], [3, 0, 1]] #第2、3行，第4、1、2列

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [149]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [150]:
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [151]:
data.loc[data.three >= 2]

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [152]:
data.loc[:, "one"] = 1

In [153]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [154]:
data.iloc[2] = 5

In [155]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [156]:
data.loc[data["four"] > 5] = 3

In [157]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [158]:
data.loc[data.three == 5, "three"] = 6

In [159]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [160]:
s1 = pd.Series([7.3, -2.5, 3.5, 1.5], index=["a", "c", "d", "e"])

In [161]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ["a", "c", "e", "f", "g"])

In [162]:
s1

a    7.3
c   -2.5
d    3.5
e    1.5
dtype: float64

In [163]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [164]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [165]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns = list("bcd"), 
                  index=["Ohio", "Texas", "Colorado"])

In [166]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list("bde"), 
                  index=["Utah", "Ohio", "Texas", "Oregon"])

In [167]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [168]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [169]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [170]:
df1 = pd.DataFrame({"A":[1,2]})

In [171]:
df2 = pd.DataFrame({"B":[3,4]})

In [172]:
df1

   A
0  1
1  2

In [173]:
df2

   B
0  3
1  4

In [174]:
df1+df2

    A   B
0 NaN NaN
1 NaN NaN

In [175]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), 
                  columns = list("abcd"))

In [176]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), 
                  columns=list("abcde"))

In [177]:
df2.loc[1, "b"] = np.nan

In [178]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [179]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [180]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [181]:
df1.add(df2, fill_value = 0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [182]:
1 / df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [183]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [184]:
df1.reindex(columns = df2.columns, fill_value = 0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [185]:
arr = np.arange(12.).reshape((3, 4))

In [186]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [187]:
arr[0]

array([0., 1., 2., 3.])

In [188]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [189]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                    columns = list("bde"), 
                    index = ["Utah", "Ohio", "Texas", "Oregon"])

In [190]:
series = frame.iloc[0]

In [191]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [192]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [193]:
frame-series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [194]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [195]:
series2

b    0
e    1
f    2
dtype: int64

In [196]:
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [197]:
series3 = frame["d"]

In [198]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [199]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [200]:
frame.sub(series3, axis = "index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [201]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), 
                    columns = list("bde"), 
                    index = ["Utah", "Ohio", "Texas", "Oregon"])

In [202]:
frame

               b         d         e
Utah    0.177952  0.030927  0.881918
Ohio    1.954390 -0.025365 -0.997375
Texas   0.350581  0.420464 -1.107356
Oregon -0.076685 -0.263545  1.619969

In [203]:
np.abs(frame)

               b         d         e
Utah    0.177952  0.030927  0.881918
Ohio    1.954390  0.025365  0.997375
Texas   0.350581  0.420464  1.107356
Oregon  0.076685  0.263545  1.619969

In [204]:
def f1(x):
    return x.max() - x.min()

In [205]:
frame.apply(f1)

b    2.031075
d    0.684009
e    2.727324
dtype: float64

In [206]:
frame.apply(f1, axis="columns")

Utah      0.850990
Ohio      2.951764
Texas     1.527819
Oregon    1.883514
dtype: float64

In [207]:
def f2(x):
    return pd.Series([x.min(), x.max()], index = ["min", "max"])

In [208]:
frame.apply(f2)

            b         d         e
min -0.076685 -0.263545 -1.107356
max  1.954390  0.420464  1.619969

In [209]:
def my_format(x):
    return f"{x:.2f}"

In [210]:
frame.applymap(my_format)

C:\Users\34327\AppData\Local\Temp\ipykernel_17260\1462544007.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)

            b      d      e
Utah     0.18   0.03   0.88
Ohio     1.95  -0.03  -1.00
Texas    0.35   0.42  -1.11
Oregon  -0.08  -0.26   1.62

In [211]:
frame["e"].map(my_format)

Utah       0.88
Ohio      -1.00
Texas     -1.11
Oregon     1.62
Name: e, dtype: object

In [212]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [213]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [214]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [215]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), 
                    index = ["three", "one"], 
                    columns = ["d", "a", "b", "c"])

In [216]:
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [217]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [218]:
frame.sort_index(axis = "columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [219]:
frame.sort_index(axis = "columns", ascending = False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [220]:
obj = pd.Series([4, 7, -3, 2])

In [221]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [222]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [223]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [224]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [225]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [226]:
obj.sort_values(na_position = "first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [227]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [228]:
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [229]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [230]:
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [231]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [232]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [233]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [234]:
obj.rank(ascending = False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [235]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1], "c" : [-2, 5, 8, -2.5]})

In [236]:
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [237]:
frame.rank(axis = "columns")#行上操作

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [238]:
frame.rank()

     b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [239]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [240]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [241]:
obj.index.is_unique

False

In [242]:
obj["a"]

a    0
a    1
dtype: int64

In [243]:
obj["c"]

np.int64(4)

In [244]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),  #生成 5 行 3 列的标准正态分布随机数（均值 0，标准差 1）
                 index = ["a", "a", "b", "b", "c"])

In [245]:
df

          0         1         2
a -0.496993  0.165920 -1.504162
a  0.212709  0.402882 -0.563828
b  0.188092  1.467427 -1.027412
b -0.271922 -0.164148 -0.566526
c -0.668039  0.005477 -1.883849

In [246]:
df.loc["b"]

          0         1         2
b  0.188092  1.467427 -1.027412
b -0.271922 -0.164148 -0.566526

In [247]:
df.loc["c"]

0   -0.668039
1    0.005477
2   -1.883849
Name: c, dtype: float64

In [248]:
In [267]: df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
                             [np.nan, np.nan], [0.75, -1.3]], 
                            index=["a", "b", "c", "d"], 
                            columns=["one", "two"])

In [249]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [250]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [251]:
df.sum(axis = "columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [252]:
df.sum(axis = "index", skipna = False)

one   NaN
two   NaN
dtype: float64

In [253]:
df.sum(axis = "columns", skipna = False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [254]:
df.mean(axis = "columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [255]:
df.idxmax()

one    b
two    d
dtype: object

In [256]:
df.idxmin()

one    d
two    b
dtype: object

In [257]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [258]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [259]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [260]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [261]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [262]:
price = pd.read_pickle("examples/yahoo_price.pkl")

In [263]:
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [264]:
returns = price.pct_change()

In [265]:
returns.tail()

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [266]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.49976361144151144)

In [267]:
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703546e-05)

In [269]:
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703546e-05)

In [270]:
returns.corr()

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [271]:
returns.cov()

          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [272]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [274]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [275]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [277]:
uniques = obj.unique()

In [278]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [279]:
uniques.sort()

In [280]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [282]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [283]:
pd.value_counts(obj.to_numpy(), sort = False)

C:\Users\34327\AppData\Local\Temp\ipykernel_17260\2072757793.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort = False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [284]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [285]:
mask = obj.isin(["b", "c"])

In [286]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [287]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
to_match = pd.Series()